config/routes.rb
Rails.application.routes.draw do
  resources :expenses
  resources :events
  get 'home/donos'
  get 'home/agenda'

  root 'home#agenda'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :expenses

  accepts_nested_attributes_for :expenses, reject_if: :all_blank, allow_destroy: true
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
    @event.expenses.build
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to home_donos_path, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to home_donos_path, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to home_donos_path, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :date_event, :responsible, :location, :situation,
        :details, :work_time, :price, :note, :ballet, expenses_attributes: [:name, :value, :_destroy])
    end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: [:show, :edit, :update, :destroy]

  # GET /expenses
  # GET /expenses.json
  def index
    @expenses = Expense.all
  end

  # GET /expenses/1
  # GET /expenses/1.json
  def show
  end

  # GET /expenses/new
  def new
    @expense = Expense.new
  end

  # GET /expenses/1/edit
  def edit
  end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = Expense.new(expense_params)

    respond_to do |format|
      if @expense.save
        format.html { redirect_to @expense, notice: 'Expense was successfully created.' }
        format.json { render :show, status: :created, location: @expense }
      else
        format.html { render :new }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to expenses_url, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_expense
      @expense = Expense.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def expense_params
      params.require(:expense).permit(:name, :value, :event_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def donos
    @events = Event.all.order('date_event asc')

  end

  def agenda
    @events = Event.all.order('date_event asc')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/helpers/home_helper.rb
module HomeHelper
  def format_date(date)
    date.strftime("%d/%m/%Y - %a - %H:%Mh")
  end

  def vouf(teste)
    if teste == true
      return "Sim"
    else
      return "Não"
    end
  end
end

app/views/events/_expense_fields.html.erb
<div class="nested-fields">
  <div class="form-group row">
    <%= f.label :name, 'Nome', :class => "col-3 col-form-label" %>
    <div class="col-9">
      <%= f.text_field :name, :class => "form-control" %>
    </div>
  </div>
  <div class="form-group row">
    <%= f.label :value, 'Valor', :class => "col-3 col-form-label" %>
    <div class="col-9">
      <%= f.text_field :value, :class => "form-control" %>
    </div>
</div>

app/views/events/_form.html.erb
<div class="container">
  <%= form_for(@event, html: { class: "basic-grey" }) do |form| %>
  <% if event.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

    <ul>
      <% event.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :name, 'Nome', :class => "col-3 col-form-label" %>
    <div class="col-9">
      <%= form.text_field :name,id: :event_name, :class => "form-control" %>
    </div>
  </div>


  <div class="form-group row">
    <%= form.label :date_event, 'Data do Evento', :class => "col-3 col-form-label"%>
    <div class="col-9">
      <%= form.datetime_select :date_event, id: :event_date_event, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :responsible, 'Empresa Responsável', :class => "col-3 col-form-label" %>
    <div class="col-9">
      <%= form.text_field :responsible, id: :event_responsible, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :location, 'Local', :class => "col-3 col-form-label" %>
    <div class="col-9">
      <%= form.text_field :location, id: :event_location, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :situation, 'Situação', :class => "col-3 col-form-label" %>
    <div class="col-9">
      <%= form.check_box :situation, id: :event_situation %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :details, 'Detalhes', :class => "col-3 col-form-label" %>
    <div class="col-9">
      <%= form.text_area :details, id: :event_details, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :work_time, 'Horas de Show', :class => "col-3 col-form-label" %>
    <div class="col-9">
      <%= form.text_field :work_time, id: :event_work_time, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :price, 'Preço do Evento', :class => "col-3 col-form-label" %>
    <div class="col-9">
      <%= form.number_field :price, id: :event_price, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :note, 'Anotações', :class => "col-3 col-form-label" %>
    <div class="col-9">
      <%= form.text_field :note, id: :event_note, :class => "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <%= form.label :ballet, 'Dançarinos', :class => "col-3 col-form-label" %>
    <div class="col-9">
      <%= form.check_box :ballet, id: :event_ballet %>
    </div>
  </div>

  <br>
  <br>


  <div id="phones">

    <%= form.fields_for :expense do |expenses_fields| %>
      <%= render partial: "expense_fields", locals: { f: expenses_fields } %>
    <% end %>

    <%= link_to_add_association('[Adicionar Custo]', form, :expenses) %>
  </div>


  <div class="actions">
    <%= form.submit 'Salvar Evento', class: "btn btn-primary" %>
  </div>

  <%end%>

</div>

app/views/events/edit.html.erb
<h1>Editando Evento</h1>

<%= render 'form', event: @event %>

<!-- <%= link_to 'Mostrar', @event %> |
<%= link_to 'Voltar', events_path %> -->

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Date event</th>
      <th>Responsible</th>
      <th>Location</th>
      <th>Situation</th>
      <th>Details</th>
      <th>Work time</th>
      <th>Price</th>
      <th>Note</th>
      <th>Ballet</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.date_event %></td>
        <td><%= event.responsible %></td>
        <td><%= event.location %></td>
        <td><%= event.situation %></td>
        <td><%= event.details %></td>
        <td><%= event.work_time %></td>
        <td><%= event.price %></td>
        <td><%= event.note %></td>
        <td><%= event.ballet %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<div class="container well">
  <h1 class="centered">Novo Evento</h1>
  <hr>
  <%= render 'form', event: @event %>

  <!-- <%= link_to 'Voltar', events_path, class: 'btn btn-danger' %> -->

</div>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Date event:</strong>
  <%= @event.date_event %>
</p>

<p>
  <strong>Responsible:</strong>
  <%= @event.responsible %>
</p>

<p>
  <strong>Location:</strong>
  <%= @event.location %>
</p>

<p>
  <strong>Situation:</strong>
  <%= @event.situation %>
</p>

<p>
  <strong>Details:</strong>
  <%= @event.details %>
</p>

<p>
  <strong>Work time:</strong>
  <%= @event.work_time %>
</p>

<p>
  <strong>Price:</strong>
  <%= @event.price %>
</p>

<p>
  <strong>Note:</strong>
  <%= @event.note %>
</p>

<p>
  <strong>Ballet:</strong>
  <%= @event.ballet %>
</p>

<%= link_to 'Editar', edit_event_path(@event) %> |
<%= link_to 'Voltar', home_donos_path %>

app/views/expenses/_form.html.erb
<%= form_with(model: expense, local: true) do |form| %>
  <% if expense.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(expense.errors.count, "error") %> prohibited this expense from being saved:</h2>

      <ul>
      <% expense.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :expense_name %>
  </div>

  <div class="field">
    <%= form.label :value %>
    <%= form.text_field :value, id: :expense_value %>
  </div>

  <div class="field">
    <%= form.label :event_id %>
    <%= form.text_field :event_id, id: :expense_event_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/expenses/edit.html.erb
<h1>Editing Expense</h1>

<%= render 'form', expense: @expense %>

<%= link_to 'Show', @expense %> |
<%= link_to 'Back', expenses_path %>

app/views/expenses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Expenses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Value</th>
      <th>Event</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @expenses.each do |expense| %>
      <tr>
        <td><%= expense.name %></td>
        <td><%= expense.value %></td>
        <td><%= expense.event %></td>
        <td><%= link_to 'Show', expense %></td>
        <td><%= link_to 'Edit', edit_expense_path(expense) %></td>
        <td><%= link_to 'Destroy', expense, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Expense', new_expense_path %>

app/views/expenses/new.html.erb
<h1>New Expense</h1>

<%= render 'form', expense: @expense %>

<%= link_to 'Back', expenses_path %>

app/views/expenses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @expense.name %>
</p>

<p>
  <strong>Value:</strong>
  <%= @expense.value %>
</p>

<p>
  <strong>Event:</strong>
  <%= @expense.event %>
</p>

<%= link_to 'Edit', edit_expense_path(@expense) %> |
<%= link_to 'Back', expenses_path %>

app/views/home/agenda.html.erb
<div class="container">

  <div class="panel panel-primary">
    <div class="panel-headind">
      <h3 class="panel-title centered">Agenda The Morô</h3>
    </div>
    <div class="panel-body">
      <table class="table table-hover" id="dev-table">
        <thead>
          <tr>
            <th>#</th>
            <th>Data</th>
            <th>Nome do Evento</th>
            <th>Responsável</th>
            <th>Local do Evento</th>
          </tr>
        </thead>
        <tbody>
          <% @events.each do |event| %>
          <tr>
            <td><%= event.id %></td>
            <td><%= l event.date_event %></td>
            <td><%= event.name %></td>
            <td><%= event.responsible %></td>
            <td><%= event.location %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

</div><!-- /.container -->

app/views/home/donos.html.erb
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="#" style="font-weight:bold;">The Morô</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Agenda<span class="sr-only">(current)</span></a>
      </li>
    </ul>
  </div>
</nav>

<div class="">
  <div class="panel panel-primary">
    <div class="panel-headind">
      <h3 class="panel-title">Eventos</h3>
    </div>
    <div class="panel-body">
      <table class="table table-hover" id="dev-table">
        <thead>
          <tr>
            <th>#</th>
            <th>Data</th>
            <th>Nome do Evento</th>
            <th>Empresa ou Responsável</th>
            <th>Local do Evento</th>
            <th>Pago</th>
            <th>Horas de duração</th>
            <th>Preço</th>
            <th>Dançarinos</th>
            <th colspan="3">Ações</th>
          </tr>
        </thead>
        <tbody>
          <% @events.each do |event| %>
          <tr>
            <td><%= event.id %></td>
            <td><%= l event.date_event %></td>
            <td><%= event.name %></td>
            <td><%= event.responsible %></td>
            <td><%= event.location %></td>
            <td><%= vouf event.situation %></td>
            <td><%= event.work_time %></td>
            <td><%= event.price %></td>
            <td><%= vouf event.ballet %></td>
            <td><%= link_to 'Ver', event, class: "btn btn-primary" %></td>
            <td><%= link_to 'Editar', edit_event_path(event), class: "btn btn-primary" %></td>
            <td><%= link_to 'Exluir', event, method: :delete, data: { confirm: 'Você tem certeza?' }, class: "btn btn-danger" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <%= link_to 'Cadastrar Evento', new_event_path, class: "btn btn-primary" %>


</div><!-- /.container -->

app/views/home/music.html.erb
<div class="container">

  <div class="panel panel-primary">
    <div class="panel-headind">
      <h3 class="panel-title centered">Agenda The Morô</h3>
    </div>
    <div class="panel-body">
      <table class="table table-hover" id="dev-table">
        <thead>
          <tr>
            <th>#</th>
            <th>Data</th>
            <th>Nome do Evento</th>
            <th>Responsável</th>
            <th>Local do Evento</th>
          </tr>
        </thead>
        <tbody>
          <% @events.each do |event| %>
          <tr>
            <td><%= event.id %></td>
            <td><%= l event.date_event %></td>
            <td><%= event.name %></td>
            <td><%= event.responsible %></td>
            <td><%= event.location %></td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>

</div><!-- /.container -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Moro</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= yield %>
  </body>
</html>